services:
  # DataBase PostgreSQL
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pern_app_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pern_app_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - pern-app-network

  # Node.js API
  server:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app # Bind mount: syncs local source code
      - server_node_modules:/app/node_modules # Named volume: protects container dependencies
    environment:
      # node-pg-migrate автоматически использует DATABASE_URL
      DATABASE_URL: postgres://postgres:postgres@db:5432/pern_app_db
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
      # Сначала накатываем миграции, потом запускаем сервер
    command: >
      sh -c "npx node-pg-migrate up -m ./src/migrations -j ts && npm run dev"
    networks:
      - pern-app-network

  # React App
  client:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - client_node_modules:/app/node_modules
    environment:
      - WDS_SOCKET_PORT=0 # Для корректного Hot Reload в Docker
        # - CHOKIDAR_USEPOLLING=true # Optional: useful for specific HMR configuration
    depends_on:
      - server
    stdin_open: true # Keeps the container running
    tty: true # Keeps the container running
    networks: 
      - pern-app-network

  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     server:
  #       condition: service_started
  #     client:
  #       condition: service_started
  #   networks:
  #     - pern-app-network

  mailpit:
    image: axllent/mailpit
    restart: always
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    environment:
      - MP_SMTP_DISABLE_RDNS=true
      - MP_DATABASE=/data/mailpit.db
      - MP_MAX_MESSAGES=5000 # Optional: auto-prune oldest messages
    volumes:
      - mailpit_data:/data
    networks:
      - pern-app-network

networks:
  pern-app-network:
    driver: bridge

volumes:
  pgdata:
  server_node_modules:  # Declare the named volume here
  client_node_modules:
  mailpit_data:
